name = "QuanticsTT"
uuid = "f7a3b90e-32db-442d-8dcb-49cd4b20b4e4"
version = "0.1.0"
authors = ["victor <victor.vanthilt@gmail.com>"]

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
DataInterpolations = "8.9.0"
QuadGK = "2.11.2"
TensorOperations = "5.4.0"
UnicodePlots = "3.8.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
