name = "QuanticsTT"
uuid = "f7a3b90e-32db-442d-8dcb-49cd4b20b4e4"
version = "0.1.0"
authors = ["victor <victor.vanthilt@gmail.com>"]

[deps]
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
TensorOperations = "5.4.0"
